graph TD
classDef Literal fill:#FFFFFF,stroke:#000000;
classDef CRM_Entity fill:#FFFFFF,stroke:#000000;
classDef Temporal_Entity fill:#82C3EC, stroke:#000000;
classDef Type fill:#FAB565, stroke:#000000;
classDef Time-Span fill:#86BCC8, stroke:#000000;
classDef Appellation fill:#FEF3BA, stroke:#000000;
classDef Place fill:#94CC7D, stroke:#000000;
classDef Persistent_Item fill:#FFFFFF, stroke:#000000;
classDef Conceptual_Object fill:#FDDC34, stroke:#000000;
classDef Physical_Thing fill:#E1BA9C, stroke:#000000;
classDef Actor fill:#ffbdca, stroke:#000000;
classDef PC_Classes fill:#cc80ff, stroke:#000000;
classDef Multi fill:#cccccc,stroke:#000000;
0["crm:E67_Birth"]:::Temporal_Entity -->|crm:P4_has_time-span| 1["crm:E52_Time-Span"]:::Time-Span
0["crm:E67_Birth"]:::Temporal_Entity -->|crm:P7_took_place_at| 2["Birth Place<br>crm:E53_Place"]:::Place
4["crm:E69_Death"]:::Temporal_Entity -->|crm:P7_took_place_at| 5["Death Place<br>crm:E53_Place"]:::Place
1["crm:E52_Time-Span"]:::Time-Span -->|crm:P82b_end_of_the_end| 11[Birth Date End<br>rdfs:Literal]:::Literal
12["crm:E52_Time-Span"]:::Time-Span -->|crm:P82b_end_of_the_end| 13[Death Date End<br>rdfs:Literal]:::Literal
1["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 22[Birth Date Begin<br>rdfs:Literal]:::Literal
7["crm:E21_Person"]:::Actor -->|crm:P100i_died_in| 4["crm:E69_Death"]:::Temporal_Entity
16["crm:E9_Move"]:::Temporal_Entity -->|crm:P26_moved_to| 20["Final Disposition Place<br>crm:E53_Place"]:::Place
12["crm:E52_Time-Span"]:::Time-Span -->|crm:P82a_begin_of_the_begin| 25[Death Date Begin<br>rdfs:Literal]:::Literal
4["crm:E69_Death"]:::Temporal_Entity -->|crm:P120_occurs_before| 16["crm:E9_Move"]:::Temporal_Entity
7["crm:E21_Person"]:::Actor -->|crm:P98i_was_born| 0["crm:E67_Birth"]:::Temporal_Entity
16["crm:E9_Move"]:::Temporal_Entity -->|crm:P25_moved| 7["crm:E21_Person"]:::Actor
4["crm:E69_Death"]:::Temporal_Entity -->|crm:P4_has_time-span| 12["crm:E52_Time-Span"]:::Time-Span
16["crm:E9_Move"]:::Temporal_Entity -->|crm:P27_moved_from| 5["Death Place<br>crm:E53_Place"]:::Place

click 2 href "https://chin-rcip.github.io/collections-model/en/semantic-paths-specification/current/entry-nodes#birthformation-place" _blank
click 5 href "https://chin-rcip.github.io/collections-model/en/semantic-paths-specification/current/entry-nodes#deathdissolution-place" _blank
click 20 href "https://chin-rcip.github.io/collections-model/en/semantic-paths-specification/current/entry-nodes#final-disposition-place" _blank
click 22 href "https://chin-rcip.github.io/collections-model/en/semantic-paths-specification/current/entry-nodes#birthformation-date-begin" _blank
click 11 href "https://chin-rcip.github.io/collections-model/en/semantic-paths-specification/current/entry-nodes#birthformation-date-end" _blank
click 13 href "https://chin-rcip.github.io/collections-model/en/semantic-paths-specification/current/entry-nodes#deathdissolution-date-end" _blank
click 25 href "https://chin-rcip.github.io/collections-model/en/semantic-paths-specification/current/entry-nodes#deathdissolution-date-begin" _blank